[deploy]
name = "flare-nevermined-oracle"
region = "us-east-1"

[build]
dockerfile = "Dockerfile"

[env]
NVM_API_KEY = ""
NVM_ENVIRONMENT = "sandbox"
NEVERMINED_APP_ID = ""
NEVERMINED_APP_SECRET = ""
NEVERMINED_PAYMENT_CHAIN = "base"
RECEIVER_ADDRESS = ""
JWT_SECRET = ""
FLARE_RPC_URL = "https://coston2-api.flare.network/ext/C/rpc"
FTSO_FEED_IDS = "0x01464c522f55534400000000000000000000000000,0x014254432f55534400000000000000000000000000"
PORT = "3000"
NODE_ENV = "production"
TEST_RPC_URL = "https://coston2-api.flare.network/ext/C/rpc"
TEST_CHAIN_ID = "114"